### ISSUE TITLE
Setup a larger / heigher display

### ISSUE THREAD

**Issue by swalter972** [tolgaatam/ColabTurtle#12]
Hi, is there a way to setup up a larger display ?
Thanks

**Comment by tolgaatam** [comment]
Yes. Sorry for not documenting it. You can supply a named parameter `initial_window_size` as a tuple to the function `initializeTurtle` like the following:

`initializeTurtle(initial_window_size=(1080,720)`

This will make the turtle display with 1080 width and 720 height.

Hope this helps.

**Comment by robderon** [comment]
Could we add this to Readme.md ?

Thanks a lot for your work

**Comment by tolgaatam** [comment]
@robderon  I have not seen the last comment of yours, as the issue was already closed. I added it to the example at README.md
