### ISSUE TITLE
color and bgcolor currently broke (incomplete?)

### ISSUE THREAD

**Issue by bdklahn** [tolgaatam/ColabTurtle#7]
I pulled the repo locally, was trying things out in a Jupyter Lab session, and got some errors.

It looks like bgcolor needs to include the c2 and c3 params.
https://github.com/tolgaatam/ColabTurtle/blob/8333d89e9922cbb7633319a0db68e8732da31170/ColabTurtle/Turtle.py#L357

I think both those functions need it to be 'c3' before the 'raise'. e.g.
https://github.com/tolgaatam/ColabTurtle/blob/8333d89e9922cbb7633319a0db68e8732da31170/ColabTurtle/Turtle.py#L363

**Comment by tolgaatam** [comment]
Upon your issue, I quickly applied a fix. Can you recheck?

**Comment by bdklahn** [comment]
Ok. I also just realized it doesn't seem to handle the case where ONLY the first argument is set.

Also, I guess I never noted that "None" should be be the default, if nothing is entered for default function args. So I guess you wouldn't need to explicitly put those in. But it never hurts to be explicit, for documenting.

**Comment by tolgaatam** [comment]
Yes, if the first parameter is not a string or tuple, it does not give any error but silently fail. I fixed that now as well

**Comment by bdklahn** [comment]
Seems to work now.

**Comment by tolgaatam** [comment]
If that fits you, i can close this issue now. We can proceed with the other issues.
